# web port
server:
#  port: ${server.port}
  port: 8081

# log config
logging:
  config: classpath:logback.xml
#  path: ${data.path}/applogs/executor/jobhandler
  path: /home/hadoop/data/web-2.1.2/packages/executor

flinkx:
  job:
    admin:
      ## flinkx admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://localhost:8080
#      addresses: http://127.0.0.1:${flinkx.admin.port}
    executor:
      appname: executor
      ip:
      port: 9999
#      port: ${executor.port:9999}
      ### job log path
      logpath: /home/hadoop/data/web-2.1.2/packages/executor/
#      logpath: ${data.path}/applogs/executor/jobhandler
      ### job log retention days
      logretentiondays: 30
    ### job, access token
    accessToken:

  executor:
    jsonpath: /home/hadoop/1.8_release/job/
#    jsonpath: ${json.path}

  shell:
    path: /home/hadoop/1.8_release/start.sh
#  pypath: ${python.path}
